---

- name: add new flavor(s)
  os_nova_flavor:
    state: present
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
  delegate_to: localhost
  become: no
  ignore_errors: yes