---
- name: disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: enable legacy network service
  service:
    name: network
    enabled: yes
    state: started

- name: reboot system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- pause:
    seconds: 5

- name: waiting for servers to come online
  wait_for_connection:

- name: copy packstack uninstall script
  copy:
    src: uninstall_packstack.sh
    dest: /root/uninstall_packstack.sh
    mode: "u+rwx,g-wx,o-rwx"

- name: install openstack-packstack package
  yum:
    name: openstack-packstack
    state: latest

- name: deploy packstack
  shell: packstack --allinone --keystone-admin-passwd={{ keystone_admin_password }}
