---
- name: disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: enable legacy network service
  service:
    name: network
    enabled: yes
    state: started

- name: enable nested kvm
  copy:
    src: kvm-intel.conf
    dest: /etc/modprobe.d/kvm-intel.conf

- name: reboot system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- pause:
    seconds: 5

- name: waiting for servers to come online
  wait_for_connection:

- name: copy packstack uninstall script
  copy:
    src: uninstall_packstack.sh
    dest: /root/uninstall_packstack.sh
    mode: "u+rwx,g-wx,o-rwx"

- name: enable openstack-packstack on CentOS
  yum:
    name: centos-release-openstack-queens
    state: latest
  when: ansible_distribution == 'CentOS'

- name: install openstack-packstack package
  yum:
    name: openstack-packstack
    state: latest

- name: deploy packstack
  shell: packstack --allinone --keystone-admin-passwd={{ keystone_admin_password }} --os-heat-install=y --os-heat-cfn-install=y --os-ceilometer-install=y --cinder-volumes-size={{ cinder_volumes_size }} --nova-libvirt-virt-type=kvm

- name: install openstack-heat-ui package
  yum:
    name: openstack-heat-ui
    state: latest
  notify: restart httpd service

# see issue: https://bugs.launchpad.net/nova/+bug/1653430
- name: fix kvm virtual type for vmware host
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^#hw_machine_type='
    insertafter: '^#hw_machine_type='
    line: 'hw_machine_type=x86_64=pc-i440fx-rhel7.2.0'
  when:
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == "VMware"

- name: set cpu mode to none to increase compatibility
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^cpu_mode=(.*)$'
    line: 'cpu_mode=none'
    backrefs: yes
  when:
    - ansible_virtualization_role == 'host'

- name: increase time out for cinder volume creation
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^block_device_allocate_retries'
    insertafter: '^#block_device_allocate_retries'
    line: 'block_device_allocate_retries=120'
    backrefs: yes