---
- name: disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: enable legacy network service
  service:
    name: network
    enabled: yes
    state: started

- name: reboot system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come online
  local_action:
    wait_for host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: 22
    search_regex: OpenSSH
    delay: 10
  become: false

- name: copy packstack uninstall script
  copy:
    src: uninstall_packstack.sh
    dest: /root/uninstall_packstack.sh
    mode: "u+rwx,g-wx,o-rwx"

- name: install openstack-packstack package
  yum:
    name: openstack-packstack
    state: latest

- name: deploy packstack
  shell: packstack --allinone --keystone-admin-passwd={{ keystone_admin_password }}
