---
- name: disable NetworkManager
  service:
    name: NetworkManager
    enabled: no
    state: stopped

- name: install network-scripts on RHEL 8
  package:
    name: network-scripts
    state: present
  when: ansible_distribution_major_version|int == 8

- name: disable decprecation warnings
  file:
    path: /etc/sysconfig/disable-deprecation-warnings
    state: touch
  when: ansible_distribution_major_version|int == 8

- name: enable legacy network service
  service:
    name: network
    enabled: yes
    state: started

- name: enable nested kvm
  copy:
    src: kvm-intel.conf
    dest: /etc/modprobe.d/kvm-intel.conf

- name: reboot system
  reboot:
    reboot_timeout: 3600

- name: copy packstack uninstall script
  copy:
    src: uninstall_packstack.sh
    dest: /root/uninstall_packstack.sh
    mode: "u+rwx,g-wx,o-rwx"

- name: enable openstack-packstack on CentOS
  yum:
    name: centos-release-openstack-{{ openstack_release_name }}
    state: latest
  when: ansible_distribution == 'CentOS'

- name: install openstack-packstack package
  yum:
    name: openstack-packstack
    state: latest

# Seems to be needed for OSP 15
- name: update python3-mako package to the latest version
  yum:
    name: python3-mako
    state: latest
    disablerepo: '*'
    enablerepo: 'openstack-*-x86_64-rpms'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8

- name: deploy packstack
  shell: packstack --allinone --keystone-admin-passwd={{ keystone_admin_password }} --os-heat-install=y --os-heat-cfn-install=y --os-ceilometer-install=y --cinder-volumes-size={{ cinder_volumes_size }} --nova-libvirt-virt-type=kvm

- name: install openstack-heat-ui package
  yum:
    name: openstack-heat-ui
    state: latest
  notify: restart httpd service

# see issue: https://bugs.launchpad.net/nova/+bug/1653430
- name: fix kvm virtual type for vmware host
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^#hw_machine_type='
    insertafter: '^#hw_machine_type='
    line: 'hw_machine_type=x86_64=pc-i440fx-rhel7.2.0'
  when:
    - ansible_virtualization_role == 'guest'
    - ansible_virtualization_type == "VMware"

# set to host-passthrough for nested virt, may need to set this to none in some cases
- name: set cpu mode to host-passthrough
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^cpu_mode=(.*)$'
    line: 'cpu_mode=host-passthrough'
    backrefs: yes
  when:
    - ansible_virtualization_role == 'host'

- name: increase time out for cinder volume creation
  lineinfile:
    path: /etc/nova/nova.conf
    regexp: '^block_device_allocate_retries=*'
    insertafter: '^#block_device_allocate_retries=*'
    line: 'block_device_allocate_retries=240'