- name: check to see if openstack compute is installed
  shell: source /root/keystonerc_admin && openstack compute service list | grep nova-compute | grep enabled
  register: check_compute
  ignore_errors: yes

- include: install.yml
  when:
    - check_compute is not success

- name: check to see if network service is installed
  shell: source /root/keystonerc_admin && openstack network list | grep private_network
  register: check_network
  ignore_errors: yes

- include: network.yml
  when:
    - check_network is not success

- include: secgroup.yml