- name: check to see if openstack compute is installed
  shell: source /root/keystonerc_admin && openstack compute service list | grep nova-compute | grep enabled
  register: check_compute
  ignore_errors: yes

- include_tasks: install.yml
  when:
    - check_compute is not success

- name: check openstack config file
  stat:
    path: "{{ config_file }}"
  register: st
  become: no
  delegate_to: localhost

- name: include openstack details
  include_vars: "{{ config_file }}"
  when: st.stat.exists and st.stat.isreg
  become: no
  delegate_to: localhost

- name: check to see if network service is installed
  shell: source /root/keystonerc_admin && openstack network list | grep private_network
  register: check_network
  ignore_errors: yes

- include_tasks: network.yml
  when:
    - check_network is not success

- include_tasks: secgroup.yml

- include_tasks: flavor.yml