---

- name: ensure router1 is deleted
  os_router:
    name: router1
    state: absent
  delegate_to: localhost
  become: no

- name: gather facts about public network
  os_networks_facts:
    name: public
  delegate_to: localhost
  become: no

- name: gather facts about ports attached to public network
  os_port_facts:
    filters:
      network_id: "{{ openstack_networks[0].id }}"
  delegate_to: localhost
  become: no
  when:
    - openstack_networks is defined
    - openstack_networks|length > 0

- name: ensure public_subnet subnet is removed
  os_subnet:
    name: public_subnet
    state: absent
  delegate_to: localhost
  become: no
  when:
    - openstack_ports is undefined or openstack_ports|length == 0

- name: ensure public network is removed
  os_network:
    name: public
    state: absent
  delegate_to: localhost
  become: no
  when:
    - openstack_ports is undefined or openstack_ports|length == 0

- name: create ifcfg-br-ex file on compute nodes
  template:
    src: ifcfg-br-ex
    dest: /etc/sysconfig/network-scripts/ifcfg-br-ex
  register: create_bridge_interface_file

- name: replace ifcfg-{{ ansible_default_ipv4.interface }} file on compute nodes
  template:
    src: ifcfg-eth0
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
  when: create_bridge_interface_file is changed

- name: reboot system
  reboot:
  when: create_bridge_interface_file is changed

- name: waiting for keystone to be available
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 5000
  delegate_to: 127.0.0.1
  become: no
  when: create_bridge_interface_file is changed

- name: ensure public network is created
  os_network:
    name: public
    state: present
    external: yes
    provider_network_type: flat
    provider_physical_network: extnet
  delegate_to: localhost
  become: no

- name: ensure public_subnet subnet is created
  os_subnet:
    name: public_subnet
    state: present
    enable_dhcp: no
    allocation_pool_start: "{{ neutron_floating_ip_start }}"
    allocation_pool_end: "{{ neutron_floating_ip_end }}"
    gateway_ip: "{{ neutron_floating_ip_gw }}"
    network_name: public
    cidr: "{{ neutron_floating_network }}"
  delegate_to: localhost
  become: no

- name: ensure private network is created
  os_network:
    name: private_network
    state: present
  delegate_to: localhost
  become: no

- name: ensure private_vmsubnet subnet is created
  os_subnet:
    name: private_vmsubnet
    state: present
    dns_nameservers: "{{ hostvars[inventory_hostname].ansible_dns.nameservers }}"
    network_name: private_network
    cidr: "{{ neutron_private_network }}"
  delegate_to: localhost
  become: no

- name: ensure router1 is created
  os_router:
    name: router1
    state: present
    network: public
    interfaces:
      - private_vmsubnet
  delegate_to: localhost
  become: no
