---
- name: clear router gateway
  shell: source /root/keystonerc_admin && openstack router unset router1 --external-gateway
  args:
    executable: /bin/bash
  ignore_errors: true

- name: delete public subnet
  shell: source /root/keystonerc_admin && openstack subnet delete public_subnet
  args:
    executable: /bin/bash
  ignore_errors: true

- name: delete public network
  shell: source /root/keystonerc_admin && openstack network delete public
  args:
    executable: /bin/bash
  ignore_errors: true

- name: determine dns server
  shell: grep -m 1 nameserver /etc/resolv.conf | awk '{ print $2}'
  register: dns

- name: create ifcfg-br-ex file on compute nodes
  template:
    src: ifcfg-br-ex
    dest: /etc/sysconfig/network-scripts/ifcfg-br-ex

- name: replace ifcfg-{{ ansible_default_ipv4.interface }} file on compute nodes
  template:
    src: ifcfg-eth0
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"

- name: reboot system
  reboot:

- name: waiting for keystone to be available
  wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 5000
  delegate_to: 127.0.0.1
  become: no

- name: create a neutron external network
  shell: source /root/keystonerc_admin && openstack network create public --provider-network-type flat --provider-physical-network extnet --external
  args:
    executable: /bin/bash

- name: create a neutron public subnet
  shell: source /root/keystonerc_admin && openstack subnet create public_subnet --no-dhcp --allocation-pool start={{ neutron_floating_ip_start }},end={{ neutron_floating_ip_end }} --gateway={{ neutron_floating_ip_gw }} --network public --subnet-range {{ neutron_floating_network }}
  args:
    executable: /bin/bash

- name: create a neutron router
  shell: source /root/keystonerc_admin && openstack router create router2
  args:
    executable: /bin/bash

- name: set the gateway for the virtual router to be the external network_type
  shell: source /root/keystonerc_admin && openstack router set --external-gateway public router2
  args:
    executable: /bin/bash

- name: create a neutron private network
  shell: source /root/keystonerc_admin && openstack network create private_network
  args:
    executable: /bin/bash

- name: create a neutron private subnet
  shell: source /root/keystonerc_admin && openstack subnet create --dns-nameserver {{ neutron_private_dns }} private_vmsubnet --network private_network --subnet-range {{ neutron_private_network }}
  args:
    executable: /bin/bash

- name: add an interface for the private subnet to the virtual router
  shell: source /root/keystonerc_admin && openstack router add subnet router2 private_vmsubnet
  args:
    executable: /bin/bash
