---

- name: get project info
  openstack.cloud.project_info:
  register: os_project_info
  delegate_to: localhost
  become: no

- name: add icmp rule to security groups
  os_security_group_rule:
    project: "{{ item.id }}"
    state: present
    security_group: default
    protocol: icmp
    port_range_min: -1
    port_range_max: -1
    remote_ip_prefix: 0.0.0.0/0
  delegate_to: localhost
  become: no
  loop: "{{ os_project_info.openstack_projects }}"

- name: add tcp rules to security groups
  os_security_group_rule:
    project: "{{ item.0.id }}"
    state: present
    security_group: default
    protocol: tcp
    port_range_min: "{{ item.1.min | default(item.1) }}"
    port_range_max: "{{ item.1.max | default(item.1.min) | default(item.1) }}"
    remote_ip_prefix: 0.0.0.0/0
  delegate_to: localhost
  become: no
  loop: "{{ os_project_info.openstack_projects|product(security_rules.tcp.ports)|list }}"

- name: add udp rules to security groups
  os_security_group_rule:
    project: "{{ item.0.id }}"
    state: present
    security_group: default
    protocol: udp
    port_range_min: "{{ item.1.min | default(item.1) }}"
    port_range_max: "{{ item.1.max | default(item.1.min) | default(item.1) }}"
    remote_ip_prefix: 0.0.0.0/0
  delegate_to: localhost
  become: no
  loop: "{{ os_project_info.openstack_projects|product(security_rules.udp.ports)|list }}"