---

- name: list security groups
  shell: source /root/keystonerc_admin && openstack security group list -f json
  register: security_groups
  ignore_errors: yes

- name: add icmp rule to security groups
  shell: source /root/keystonerc_admin && openstack security group rule create --protocol ICMP --ingress {{ item.ID }}
  with_items:
    - "{{ security_groups.stdout }}"
  ignore_errors: yes

- name: add tcp rules to security groups
  shell: source /root/keystonerc_admin && openstack security group rule create --protocol TCP --dst-port {{ item.1 }} --ingress {{ item.0.ID }}
  with_nested:
    - "{{ security_groups.stdout }}"
    - "{{ security_rules.tcp.ports }}"
  ignore_errors: yes

- name: add udp rules to security groups
  shell: source /root/keystonerc_admin && openstack security group rule create --protocol UDP --dst-port {{ item.1 }} --ingress {{ item.0.ID }}
  with_nested:
    - "{{ security_groups.stdout }}"
    - "{{ security_rules.udp.ports }}"
  ignore_errors: yes
