---

- name: add new flavor
  shell: source /root/keystonerc_admin && neutron security-group-rule-create --protocol udp --port-range-min {{ item[1] }} --port-range-max {{ item[1] }} --direction ingress {{ item[0].id }}
  with_nested:
    - "{{ security_groups.stdout }}"
    - "{{ security_rules.udp.ports }}"
  ignore_errors: yes
